disabled_rules: 
  - trailing_comma
  - identifier_name
  - todo
  - force_try
  - large_tuple
  - force_cast
  - type_name
  - type_body_length
  - line_length
  - file_length
  - function_body_length
  - cyclomatic_complexity
