version: '3.7'
services:
  test:
    build:
      context: .
      target: build
      dockerfile: Dockerfile-test
    image: swiftxgboost
    volumes:
      - "./:/app"
    command: swift test

  documentation:
    build:
      context: .
      target: build
      dockerfile: Dockerfile-test
    image: swiftxgboost
    volumes:
      - "./:/app"
    command: swift-doc generate ./Sources --module-name XGBoost --base-url https://github.com/kongzii/SwiftXGBoost/wiki --output Documentation
