version: '3.7'
services:
  swiftxgboost:
    build:
      context: .
      target: build
    image: swiftxgboost
    volumes:
      - "./:/app"

  test:
    build:
      context: .
      target: build
    image: swiftxgboost
    volumes:
      - "./:/app"
    command: swift test
