name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  Tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -t swiftxgboost-tests -f Dockerfile-test .
      - name: Run tests
        run: docker run swiftxgboost-tests
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SwiftLint with --strict
        uses: norio-nomura/action-swiftlint@3.1.0
        with:
          args: --strict
  SwiftFormat:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies from brew
        run: brew install swiftformat
      - name: Run formatting
        run: swiftformat .
      - name: Run git diff
        run: git diff --exit-code
