name: Main

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  UbuntuTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Build
        run: docker build -t swiftxgboost-tests .
      - name: Run tests
        run: docker run swiftxgboost-tests
  CodeCoverageAndMacOSTests:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies from brew
        run: brew install xgboost python3
      - name: Install dependencies for python
        run: pip3 install xgboost coverage
      - name: Test and create CodeCoverage
        run: swift test --enable-code-coverage
      - name: Upload CodeCoverage
        run: bash <(curl -s https://codecov.io/bash) -f $(swift test --show-codecov-path)
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
  SwiftFormat:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Install dependencies from brew
        run: brew install swiftformat
      - name: Run formatting
        run: swiftformat .
      - name: Run git diff
        run: git diff --exit-code
